// Generated by gencpp from file sunray_msgs/agent_state.msg
// DO NOT EDIT!


#ifndef SUNRAY_MSGS_MESSAGE_AGENT_STATE_H
#define SUNRAY_MSGS_MESSAGE_AGENT_STATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Quaternion.h>

namespace sunray_msgs
{
template <class ContainerAllocator>
struct agent_state_
{
  typedef agent_state_<ContainerAllocator> Type;

  agent_state_()
    : header()
    , agent_type(0)
    , agent_id(0)
    , agent_ip()
    , connected(false)
    , odom_valid(false)
    , pos()
    , vel()
    , att()
    , attitude_q()
    , battery(0.0)
    , control_state(0)  {
      pos.assign(0.0);

      vel.assign(0.0);

      att.assign(0.0);
  }
  agent_state_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , agent_type(0)
    , agent_id(0)
    , agent_ip(_alloc)
    , connected(false)
    , odom_valid(false)
    , pos()
    , vel()
    , att()
    , attitude_q(_alloc)
    , battery(0.0)
    , control_state(0)  {
  (void)_alloc;
      pos.assign(0.0);

      vel.assign(0.0);

      att.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _agent_type_type;
  _agent_type_type agent_type;

   typedef uint8_t _agent_id_type;
  _agent_id_type agent_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _agent_ip_type;
  _agent_ip_type agent_ip;

   typedef uint8_t _connected_type;
  _connected_type connected;

   typedef uint8_t _odom_valid_type;
  _odom_valid_type odom_valid;

   typedef boost::array<float, 3>  _pos_type;
  _pos_type pos;

   typedef boost::array<float, 3>  _vel_type;
  _vel_type vel;

   typedef boost::array<float, 3>  _att_type;
  _att_type att;

   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _attitude_q_type;
  _attitude_q_type attitude_q;

   typedef float _battery_type;
  _battery_type battery;

   typedef uint8_t _control_state_type;
  _control_state_type control_state;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(RMTT)
  #undef RMTT
#endif
#if defined(_WIN32) && defined(TIANBOT)
  #undef TIANBOT
#endif
#if defined(_WIN32) && defined(WHEELTEC)
  #undef WHEELTEC
#endif
#if defined(_WIN32) && defined(SIKONG)
  #undef SIKONG
#endif

  enum {
    RMTT = 0u,
    TIANBOT = 1u,
    WHEELTEC = 2u,
    SIKONG = 3u,
  };


  typedef boost::shared_ptr< ::sunray_msgs::agent_state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sunray_msgs::agent_state_<ContainerAllocator> const> ConstPtr;

}; // struct agent_state_

typedef ::sunray_msgs::agent_state_<std::allocator<void> > agent_state;

typedef boost::shared_ptr< ::sunray_msgs::agent_state > agent_statePtr;
typedef boost::shared_ptr< ::sunray_msgs::agent_state const> agent_stateConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sunray_msgs::agent_state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sunray_msgs::agent_state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sunray_msgs::agent_state_<ContainerAllocator1> & lhs, const ::sunray_msgs::agent_state_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.agent_type == rhs.agent_type &&
    lhs.agent_id == rhs.agent_id &&
    lhs.agent_ip == rhs.agent_ip &&
    lhs.connected == rhs.connected &&
    lhs.odom_valid == rhs.odom_valid &&
    lhs.pos == rhs.pos &&
    lhs.vel == rhs.vel &&
    lhs.att == rhs.att &&
    lhs.attitude_q == rhs.attitude_q &&
    lhs.battery == rhs.battery &&
    lhs.control_state == rhs.control_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sunray_msgs::agent_state_<ContainerAllocator1> & lhs, const ::sunray_msgs::agent_state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sunray_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sunray_msgs::agent_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sunray_msgs::agent_state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sunray_msgs::agent_state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sunray_msgs::agent_state_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sunray_msgs::agent_state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sunray_msgs::agent_state_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sunray_msgs::agent_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "adb46b835ede27744c5ee8dbd1eaf160";
  }

  static const char* value(const ::sunray_msgs::agent_state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xadb46b835ede2774ULL;
  static const uint64_t static_value2 = 0x4c5ee8dbd1eaf160ULL;
};

template<class ContainerAllocator>
struct DataType< ::sunray_msgs::agent_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sunray_msgs/agent_state";
  }

  static const char* value(const ::sunray_msgs::agent_state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sunray_msgs::agent_state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"## 基本状态\n"
"uint8 agent_type              ## 智能体类型\n"
"uint8 agent_id                ## 智能体编号\n"
"string agent_ip                 ## 智能体IP\n"
"bool connected                ## 是否连接上智能体驱动\n"
"bool odom_valid               ## 是否收到动捕数据\n"
"\n"
"## 智能体位置、速度、姿态\n"
"float32[3] pos                 ## [m]\n"
"float32[3] vel                 ## [m/s]\n"
"float32[3] att                 ## [rad]\n"
"geometry_msgs/Quaternion attitude_q ## 四元数\n"
"\n"
"## 智能体电池状态\n"
"float32 battery                ## [0-1]\n"
"\n"
"## 智能体控制状态\n"
"uint8 control_state\n"
"\n"
"## agent_type枚举\n"
"uint8 RMTT = 0\n"
"uint8 TIANBOT = 1\n"
"uint8 WHEELTEC = 2\n"
"uint8 SIKONG = 3\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::sunray_msgs::agent_state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sunray_msgs::agent_state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.agent_type);
      stream.next(m.agent_id);
      stream.next(m.agent_ip);
      stream.next(m.connected);
      stream.next(m.odom_valid);
      stream.next(m.pos);
      stream.next(m.vel);
      stream.next(m.att);
      stream.next(m.attitude_q);
      stream.next(m.battery);
      stream.next(m.control_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct agent_state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sunray_msgs::agent_state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sunray_msgs::agent_state_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "agent_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.agent_type);
    s << indent << "agent_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.agent_id);
    s << indent << "agent_ip: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.agent_ip);
    s << indent << "connected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.connected);
    s << indent << "odom_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.odom_valid);
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pos[i]);
    }
    s << indent << "vel[]" << std::endl;
    for (size_t i = 0; i < v.vel.size(); ++i)
    {
      s << indent << "  vel[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.vel[i]);
    }
    s << indent << "att[]" << std::endl;
    for (size_t i = 0; i < v.att.size(); ++i)
    {
      s << indent << "  att[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.att[i]);
    }
    s << indent << "attitude_q: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.attitude_q);
    s << indent << "battery: ";
    Printer<float>::stream(s, indent + "  ", v.battery);
    s << indent << "control_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUNRAY_MSGS_MESSAGE_AGENT_STATE_H
