// Generated by gencpp from file sunray_msgs/orca_cmd.msg
// DO NOT EDIT!


#ifndef SUNRAY_MSGS_MESSAGE_ORCA_CMD_H
#define SUNRAY_MSGS_MESSAGE_ORCA_CMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sunray_msgs
{
template <class ContainerAllocator>
struct orca_cmd_
{
  typedef orca_cmd_<ContainerAllocator> Type;

  orca_cmd_()
    : header()
    , orca_cmd(0)
    , scenario_id(0)  {
    }
  orca_cmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , orca_cmd(0)
    , scenario_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _orca_cmd_type;
  _orca_cmd_type orca_cmd;

   typedef uint8_t _scenario_id_type;
  _scenario_id_type scenario_id;





  typedef boost::shared_ptr< ::sunray_msgs::orca_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sunray_msgs::orca_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct orca_cmd_

typedef ::sunray_msgs::orca_cmd_<std::allocator<void> > orca_cmd;

typedef boost::shared_ptr< ::sunray_msgs::orca_cmd > orca_cmdPtr;
typedef boost::shared_ptr< ::sunray_msgs::orca_cmd const> orca_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sunray_msgs::orca_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sunray_msgs::orca_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sunray_msgs::orca_cmd_<ContainerAllocator1> & lhs, const ::sunray_msgs::orca_cmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.orca_cmd == rhs.orca_cmd &&
    lhs.scenario_id == rhs.scenario_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sunray_msgs::orca_cmd_<ContainerAllocator1> & lhs, const ::sunray_msgs::orca_cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sunray_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sunray_msgs::orca_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sunray_msgs::orca_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sunray_msgs::orca_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sunray_msgs::orca_cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sunray_msgs::orca_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sunray_msgs::orca_cmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sunray_msgs::orca_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1d519fdc68c652710d2bdf69a489838";
  }

  static const char* value(const ::sunray_msgs::orca_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1d519fdc68c6527ULL;
  static const uint64_t static_value2 = 0x10d2bdf69a489838ULL;
};

template<class ContainerAllocator>
struct DataType< ::sunray_msgs::orca_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sunray_msgs/orca_cmd";
  }

  static const char* value(const ::sunray_msgs::orca_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sunray_msgs::orca_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"## 状态机指令\n"
"uint8 orca_cmd   \n"
"uint8 scenario_id           \n"
" \n"
"\n"
"\n"
"\n"
"\n"
"\n"
"    \n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sunray_msgs::orca_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sunray_msgs::orca_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.orca_cmd);
      stream.next(m.scenario_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct orca_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sunray_msgs::orca_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sunray_msgs::orca_cmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "orca_cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.orca_cmd);
    s << indent << "scenario_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.scenario_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUNRAY_MSGS_MESSAGE_ORCA_CMD_H
