// Generated by gencpp from file sunray_msgs/station_cmd.msg
// DO NOT EDIT!


#ifndef SUNRAY_MSGS_MESSAGE_STATION_CMD_H
#define SUNRAY_MSGS_MESSAGE_STATION_CMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace sunray_msgs
{
template <class ContainerAllocator>
struct station_cmd_
{
  typedef station_cmd_<ContainerAllocator> Type;

  station_cmd_()
    : header()
    , uav_id(0)
    , mission_state(0)
    , scenario_id(0)  {
    }
  station_cmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , uav_id(0)
    , mission_state(0)
    , scenario_id(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _uav_id_type;
  _uav_id_type uav_id;

   typedef uint8_t _mission_state_type;
  _mission_state_type mission_state;

   typedef uint8_t _scenario_id_type;
  _scenario_id_type scenario_id;





  typedef boost::shared_ptr< ::sunray_msgs::station_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sunray_msgs::station_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct station_cmd_

typedef ::sunray_msgs::station_cmd_<std::allocator<void> > station_cmd;

typedef boost::shared_ptr< ::sunray_msgs::station_cmd > station_cmdPtr;
typedef boost::shared_ptr< ::sunray_msgs::station_cmd const> station_cmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sunray_msgs::station_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sunray_msgs::station_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sunray_msgs::station_cmd_<ContainerAllocator1> & lhs, const ::sunray_msgs::station_cmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.uav_id == rhs.uav_id &&
    lhs.mission_state == rhs.mission_state &&
    lhs.scenario_id == rhs.scenario_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sunray_msgs::station_cmd_<ContainerAllocator1> & lhs, const ::sunray_msgs::station_cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sunray_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sunray_msgs::station_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sunray_msgs::station_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sunray_msgs::station_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sunray_msgs::station_cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sunray_msgs::station_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sunray_msgs::station_cmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sunray_msgs::station_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9fbf99fef9ff42ede4e5c27986fb1df";
  }

  static const char* value(const ::sunray_msgs::station_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9fbf99fef9ff42eULL;
  static const uint64_t static_value2 = 0xde4e5c27986fb1dfULL;
};

template<class ContainerAllocator>
struct DataType< ::sunray_msgs::station_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sunray_msgs/station_cmd";
  }

  static const char* value(const ::sunray_msgs::station_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sunray_msgs::station_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"## 对于起飞、降落、悬停、ORCA_RUN指令：当指定ID的时候，只有指定的ID响应\n"
"## 对于其他指令，uav_id设置为99，所有飞机响应该状态  \n"
"uint8 uav_id  \n"
"\n"
"## 状态机指令\n"
"uint8 mission_state   \n"
"uint8 scenario_id           \n"
" \n"
"\n"
"\n"
"\n"
"\n"
"\n"
"    \n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::sunray_msgs::station_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sunray_msgs::station_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.uav_id);
      stream.next(m.mission_state);
      stream.next(m.scenario_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct station_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sunray_msgs::station_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sunray_msgs::station_cmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "uav_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.uav_id);
    s << indent << "mission_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mission_state);
    s << indent << "scenario_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.scenario_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUNRAY_MSGS_MESSAGE_STATION_CMD_H
