# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sunray_msgs/orca_state.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class orca_state(genpy.Message):
  _md5sum = "94cd23020ece232971ee6a1b721a7e0d"
  _type = "sunray_msgs/orca_state"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

## 基本状态
uint8 mission_state
## 基本状态
uint8 uav_id                ## 无人机编号
## 是否到达目标点
bool arrived_goal
## 是否到达目标点
bool arrived_all_goal
## 目标位置
float32[2] goal                 ## [m]
## ORCA期望速度
float32[2] vel_orca                 ## [m/s]





    

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','mission_state','uav_id','arrived_goal','arrived_all_goal','goal','vel_orca']
  _slot_types = ['std_msgs/Header','uint8','uint8','bool','bool','float32[2]','float32[2]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,mission_state,uav_id,arrived_goal,arrived_all_goal,goal,vel_orca

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(orca_state, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.mission_state is None:
        self.mission_state = 0
      if self.uav_id is None:
        self.uav_id = 0
      if self.arrived_goal is None:
        self.arrived_goal = False
      if self.arrived_all_goal is None:
        self.arrived_all_goal = False
      if self.goal is None:
        self.goal = [0.] * 2
      if self.vel_orca is None:
        self.vel_orca = [0.] * 2
    else:
      self.header = std_msgs.msg.Header()
      self.mission_state = 0
      self.uav_id = 0
      self.arrived_goal = False
      self.arrived_all_goal = False
      self.goal = [0.] * 2
      self.vel_orca = [0.] * 2

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4B().pack(_x.mission_state, _x.uav_id, _x.arrived_goal, _x.arrived_all_goal))
      buff.write(_get_struct_2f().pack(*self.goal))
      buff.write(_get_struct_2f().pack(*self.vel_orca))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 4
      (_x.mission_state, _x.uav_id, _x.arrived_goal, _x.arrived_all_goal,) = _get_struct_4B().unpack(str[start:end])
      self.arrived_goal = bool(self.arrived_goal)
      self.arrived_all_goal = bool(self.arrived_all_goal)
      start = end
      end += 8
      self.goal = _get_struct_2f().unpack(str[start:end])
      start = end
      end += 8
      self.vel_orca = _get_struct_2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4B().pack(_x.mission_state, _x.uav_id, _x.arrived_goal, _x.arrived_all_goal))
      buff.write(self.goal.tostring())
      buff.write(self.vel_orca.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 4
      (_x.mission_state, _x.uav_id, _x.arrived_goal, _x.arrived_all_goal,) = _get_struct_4B().unpack(str[start:end])
      self.arrived_goal = bool(self.arrived_goal)
      self.arrived_all_goal = bool(self.arrived_all_goal)
      start = end
      end += 8
      self.goal = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=2)
      start = end
      end += 8
      self.vel_orca = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=2)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
