# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sunray_msgs/rmtt_cmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class rmtt_cmd(genpy.Message):
  _md5sum = "a1941fe70865cfa39c036a2c1ad0339a"
  _type = "sunray_msgs/rmtt_cmd"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

## 当指定ID的时候，只有指定的ID响应
uint8 agent_id  

## 状态机指令
uint8 control_state   

## 期望位置、偏航角 -> 对应POS_CONTROL模式
geometry_msgs/Point desired_pos    ## [m]
float32 desired_yaw                 ## [rad]

## 期望速度 -> 对应VEL_CONTROL模式
geometry_msgs/Twist desired_vel






    

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['header','agent_id','control_state','desired_pos','desired_yaw','desired_vel']
  _slot_types = ['std_msgs/Header','uint8','uint8','geometry_msgs/Point','float32','geometry_msgs/Twist']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,agent_id,control_state,desired_pos,desired_yaw,desired_vel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(rmtt_cmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.agent_id is None:
        self.agent_id = 0
      if self.control_state is None:
        self.control_state = 0
      if self.desired_pos is None:
        self.desired_pos = geometry_msgs.msg.Point()
      if self.desired_yaw is None:
        self.desired_yaw = 0.
      if self.desired_vel is None:
        self.desired_vel = geometry_msgs.msg.Twist()
    else:
      self.header = std_msgs.msg.Header()
      self.agent_id = 0
      self.control_state = 0
      self.desired_pos = geometry_msgs.msg.Point()
      self.desired_yaw = 0.
      self.desired_vel = geometry_msgs.msg.Twist()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B3df6d().pack(_x.agent_id, _x.control_state, _x.desired_pos.x, _x.desired_pos.y, _x.desired_pos.z, _x.desired_yaw, _x.desired_vel.linear.x, _x.desired_vel.linear.y, _x.desired_vel.linear.z, _x.desired_vel.angular.x, _x.desired_vel.angular.y, _x.desired_vel.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.desired_pos is None:
        self.desired_pos = geometry_msgs.msg.Point()
      if self.desired_vel is None:
        self.desired_vel = geometry_msgs.msg.Twist()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 78
      (_x.agent_id, _x.control_state, _x.desired_pos.x, _x.desired_pos.y, _x.desired_pos.z, _x.desired_yaw, _x.desired_vel.linear.x, _x.desired_vel.linear.y, _x.desired_vel.linear.z, _x.desired_vel.angular.x, _x.desired_vel.angular.y, _x.desired_vel.angular.z,) = _get_struct_2B3df6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B3df6d().pack(_x.agent_id, _x.control_state, _x.desired_pos.x, _x.desired_pos.y, _x.desired_pos.z, _x.desired_yaw, _x.desired_vel.linear.x, _x.desired_vel.linear.y, _x.desired_vel.linear.z, _x.desired_vel.angular.x, _x.desired_vel.angular.y, _x.desired_vel.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.desired_pos is None:
        self.desired_pos = geometry_msgs.msg.Point()
      if self.desired_vel is None:
        self.desired_vel = geometry_msgs.msg.Twist()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 78
      (_x.agent_id, _x.control_state, _x.desired_pos.x, _x.desired_pos.y, _x.desired_pos.z, _x.desired_yaw, _x.desired_vel.linear.x, _x.desired_vel.linear.y, _x.desired_vel.linear.z, _x.desired_vel.angular.x, _x.desired_vel.angular.y, _x.desired_vel.angular.z,) = _get_struct_2B3df6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B3df6d = None
def _get_struct_2B3df6d():
    global _struct_2B3df6d
    if _struct_2B3df6d is None:
        _struct_2B3df6d = struct.Struct("<2B3df6d")
    return _struct_2B3df6d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
